### 3. `script.js`
```javascript
const ramos = [
  { codigo: "BIOL034", nombre: "Biología Celular", prereqs: [], semestre: "1° Semestre" },
  { codigo: "BIOL035", nombre: "Lab. Biología Celular", prereqs: [], semestre: "1° Semestre" },
  { codigo: "DEBD221", nombre: "Zoología", prereqs: [], semestre: "1° Semestre" },
  { codigo: "FMMP003", nombre: "Matemática", prereqs: [], semestre: "1° Semestre" },
  { codigo: "MVET611", nombre: "Introducción a la Medicina Veterinaria", prereqs: [], semestre: "1° Semestre" },
  { codigo: "QUI002", nombre: "Química", prereqs: [], semestre: "1° Semestre" },
  { codigo: "BIOL166", nombre: "Bioquímica", prereqs: ["BIOL034", "BIOL035", "QUI002"], semestre: "2° Semestre" },
  { codigo: "CEGHC11", nombre: "Habilidades Comunicativas", prereqs: [], semestre: "2° Semestre" },
  { codigo: "ING119", nombre: "Inglés I", prereqs: [], semestre: "2° Semestre" },
  { codigo: "MVET621", nombre: "ADO I", prereqs: ["BIOL034", "BIOL035"], semestre: "2° Semestre" },
  { codigo: "MVET622", nombre: "Cuerpo Animal I", prereqs: ["BIOL034", "BIOL035", "DEBD221"], semestre: "2° Semestre" },
  { codigo: "DEBD130", nombre: "Métodos Cuantitativos RR.NN", prereqs: ["FMMP003"], semestre: "3° Semestre" },
  { codigo: "ING129", nombre: "Inglés II", prereqs: ["ING119"], semestre: "3° Semestre" },
  { codigo: "MVET631", nombre: "ADO II", prereqs: ["BIOL166", "MVET621"], semestre: "3° Semestre" },
  { codigo: "MVET632", nombre: "Cuerpo Animal II", prereqs: ["MVET622"], semestre: "3° Semestre" },
  { codigo: "MVET633", nombre: "FDO I", prereqs: ["MVET622"], semestre: "3° Semestre" },
  { codigo: "DEBD140", nombre: "Ecología General", prereqs: ["DEBD130"], semestre: "4° Semestre" },
  { codigo: "ING239", nombre: "Inglés III", prereqs: ["ING129"], semestre: "4° Semestre" },
  { codigo: "MVET178", nombre: "Genética", prereqs: ["DEBD130", "BIOL166"], semestre: "4° Semestre" },
  { codigo: "MVET240", nombre: "Anatomía Clínica", prereqs: ["MVET632", "MVET633"], semestre: "4° Semestre" },
  { codigo: "MVET641", nombre: "FDO II", prereqs: ["MVET633", "MVET631"], semestre: "4° Semestre" },
  { codigo: "DEBD160", nombre: "Biología de la Conservación", prereqs: ["DEBD140"], semestre: "5° Semestre" },
  { codigo: "ING249", nombre: "Inglés IV", prereqs: ["ING239"], semestre: "5° Semestre" },
  { codigo: "MVET192", nombre: "Farmacología", prereqs: ["MVET641"], semestre: "5° Semestre" },
  { codigo: "MVET340", nombre: "Enfermedades de Org. Acuáticos", prereqs: ["MVET631"], semestre: "5° Semestre" },
  { codigo: "MVET651", nombre: "Anatomía Patológica", prereqs: ["MVET632", "MVET641"], semestre: "5° Semestre" },
  { codigo: "MVET652", nombre: "Nutrición y Alimentación Animal", prereqs: ["MVET240"], semestre: "5° Semestre" },
  { codigo: "CEGCT12", nombre: "Razonamiento Científico", prereqs: ["CEGHC11"], semestre: "6° Semestre" },
  { codigo: "MVET230", nombre: "Patología Clínica", prereqs: ["MVET240", "MVET641"], semestre: "6° Semestre" },
  { codigo: "MVET310", nombre: "Imagenología", prereqs: ["MVET651"], semestre: "6° Semestre" },
  { codigo: "MVET440", nombre: "Epidemiología y Salud Pública", prereqs: ["DEBD130", "MVET641"], semestre: "6° Semestre" },
  { codigo: "MVET661", nombre: "Reproducción", prereqs: ["MVET633", "MVET632"], semestre: "6° Semestre" },
  { codigo: "DEBD161", nombre: "Manejo de Fauna Silvestre", prereqs: ["DEBD160", "MVET633"], semestre: "7° Semestre" },
  { codigo: "IAMB662", nombre: "Legislación y Eval. Ambiental", prereqs: ["DEBD140", "DEBD160"], semestre: "7° Semestre" },
  { codigo: "MVET671", nombre: "Inocuidad de Alimentos", prereqs: ["MVET440"], semestre: "7° Semestre" },
  { codigo: "MVET673", nombre: "Medicina", prereqs: ["MVET641", "MVET240", "MVET192"], semestre: "7° Semestre" },
  { codigo: "MVET674", nombre: "Sistemas de Producción Animal", prereqs: ["MVET652", "MVET661", "MVET340"], semestre: "7° Semestre" },
  { codigo: "DEBD180", nombre: "Formulación Proyectos RRNN", prereqs: ["IAMB662"], semestre: "8° Semestre" },
  { codigo: "MVET280", nombre: "Cirugía", prereqs: ["MVET673", "MVET310"], semestre: "8° Semestre" },
  { codigo: "MVET370", nombre: "Zoonosis y Enf. Emergentes", prereqs: ["MVET671"], semestre: "8° Semestre" },
  { codigo: "MVET681", nombre: "Patobiología Molecular", prereqs: ["MVET230"], semestre: "8° Semestre" },
  { codigo: "MVET682", nombre: "Práctica Profesional", prereqs: ["MVET310", "MVET673"], semestre: "8° Semestre" },
  { codigo: "CEGPC13", nombre: "Pensamiento Crítico", prereqs: ["CEGCT12", "CEGHC11"], semestre: "9° Semestre" },
  { codigo: "MVET691", nombre: "Ética y Bienestar Animal", prereqs: ["MVET674", "DEBD161"], semestre: "9° Semestre" },
  { codigo: "MVET692", nombre: "Innovación y Transferencia", prereqs: ["DEBD180"], semestre: "9° Semestre" },
  { codigo: "MVET693", nombre: "Clínica", prereqs: ["MVET280", "MVET230"], semestre: "9° Semestre" },
  { codigo: "MVET694", nombre: "Proyecto de Título", prereqs: ["MVET370", "MVET280", "MVET681", "DEBD180", "MVET682"], semestre: "9° Semestre" },
  { codigo: "CEGRS14", nombre: "Responsabilidad Social", prereqs: ["CEGPC13"], semestre: "10° Semestre" },
  { codigo: "MVET695", nombre: "Electivo Profesional I", prereqs: ["MVET370", "MVET681", "DEBD180", "MVET682", "MVET693"], semestre: "10° Semestre" },
  { codigo: "MVET696", nombre: "Electivo Profesional II", prereqs: ["MVET370", "MVET280", "MVET681", "DEBD180", "MVET682"], semestre: "10° Semestre" },
  { codigo: "MVET697", nombre: "Internado", prereqs: ["MVET693", "MVET691"], semestre: "10° Semestre" }
];
